scope/format:
  - any: ['lib/mix_machine/format/*']

scope/tasks:
  - any: ['lib/mix/tasks/*']

scope/ci:
  - any: ['.github/workflows/*']

scope/test:
  - any: ['test/**/*', '!test/fixtures/**/*']

scope/test/fixtures:
  - any: ['test/fixtures/**/*']
