name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp_version: ['24.0', '23.3', '22.3']
        elixir_version: ['1.10.3', '1.11.4', '1.12.1']
        rebar3_version: ['3.15.2']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        elixir-version: ${{ matrix.elixir_version }}
        rebar3-version: ${{ matrix.rebar3_version }}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix do deps.get, deps.compile
    - name: Run tests
      run: mix test

  serif-test:
    name: Try to upload Serif report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp_version: ['24.0', '23.3', '22.3']
        elixir_version: ['1.10.3', '1.11.4', '1.12.1']
        rebar3_version: ['3.15.2']
        project: ['example_a']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        elixir-version: ${{ matrix.elixir_version }}
        rebar3-version: ${{ matrix.rebar3_version }}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix do deps.get, deps.compile
      working-directory: test/fixtures/${{ matrix.project }}
    - name: Run tests
      run: mix compile.machine --format sarif --output results.sarif
      working-directory: test/fixtures/${{ matrix.project }}
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: test/fixtures/${{ matrix.project }}/results.sarif
